version: '3.1'

services: 
  localstack:
    image: localstack/localstack:latest
    ports: 
      - '4566:4566'
    environment: 
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566 # container internal edge port
      - SERVICES=lambda,s3,cloudformation,sts,apigateway,iam
    volumes: 
      - "${TEMPDIR:-/tmp/localstack}:/temp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"